const API=localStorage.getItem('SCANNER_API')||'http://127.0.0.1:8000';let lastResults=[],chart;
const $=id=>document.getElementById(id);const api=async(p,opt={})=>{const r=await fetch(API+p,opt);if(!r.ok)throw new Error(await r.text());return r.json()};
async function init(){try{const [tfs,scs]=await Promise.all([api('/api/timeframes'),api('/api/scanners')]);$('timeframe').innerHTML=tfs.map(x=>`<option ${x==='Daily'?'selected':''}>${x}</option>`).join('');$('scanner').innerHTML=scs.map(x=>`<option>${x.name}</option>`).join('');window.SCANNERS=scs;renderTiles();await Promise.all([loadSymbols(),loadCandles()]);$('analysisDate').value=new Date().toISOString().slice(0,10);$('status').textContent='🟢 Ready. Select scanner and run.'}catch(e){$('status').textContent='🔴 API connection error: '+e.message}}
function renderTiles(){const s=$('scanner').value;$('scannerTiles').innerHTML=SCANNERS.map(x=>`<div class="tile ${x.name===s?'active':''}" style="background:${x.color}" data-s="${x.name}">${x.name}</div>`).join('');document.querySelectorAll('.tile').forEach(e=>e.onclick=()=>{$('scanner').value=e.dataset.s;renderTiles()})}
async function loadSymbols(){const a=await api('/api/symbols?timeframe='+encodeURIComponent($('timeframe').value));$('symbol').innerHTML=a.map(x=>`<option>${x}</option>`).join('')}
async function loadCandles(){const d=await api('/api/last-candles');$('candleCards').innerHTML=Object.entries(d).map(([k,v])=>`<div class="card"><b>${k}</b><span>${v?new Date(v).toLocaleString('en-IN',{timeZone:'Asia/Kolkata'}):'No data'}</span></div>`).join('')}
function bodyFor(r){return JSON.stringify({scanner:$('scanner').value,timeframe:$('timeframe').value,analysis_date:$('analysisDate').value})}
async function run(){try{$('status').textContent='⏳ Scanner calculation running…';const d=await api('/api/scan',{method:'POST',headers:{'Content-Type':'application/json'},body:bodyFor()});lastResults=d.results;$('resultTitle').textContent=`${d.scanner} — ${d.total_matches} Matches`;renderTable(lastResults);renderChart(d.zones);$('status').textContent=`🟢 Completed for ${d.analysis_date} • ${d.total_matches} matches`}catch(e){$('status').textContent='🔴 Scan failed: '+e.message}}
function renderTable(rows){const cols=['Symbol','Signal','Trend','State','Setup','Divergence','RSI','Zone','Confluence','Bias','Probability','TV_Link'];$('resultsTable').querySelector('thead').innerHTML='<tr>'+cols.map(c=>`<th>${c}</th>`).join('')+'</tr>';$('resultsTable').querySelector('tbody').innerHTML=rows.map(r=>'<tr>'+cols.map(c=>{let v=r[c]??'';if(c==='TV_Link'&&v)return `<td><a target="_blank" href="${String(v).replace(/^\[TV\]\((.*)\)$/,'$1')}">📈 TV</a></td>`;const cl=c==='Bias'?(String(v)==='Bullish'?'bull':String(v)==='Bearish'?'bear':''):'';return `<td class="${cl}">${v}</td>`}).join('')+'</tr>').join('')}
function renderChart(z){if(chart)chart.destroy();const labels=Object.keys(z||{}),vals=Object.values(z||{});chart=new Chart($('rsiChart'),{type:'doughnut',data:{labels,datasets:[{data:vals}]},options:{plugins:{title:{display:true,text:'RSI Market Pulse Distribution'}}}})}
async function matrix(){try{$('matrix').textContent='⏳ Calculating all scanners…';const d=await api('/api/matrix',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({symbol:$('symbol').value,timeframe:$('timeframe').value,analysis_date:$('analysisDate').value})});$('matrix').innerHTML=d.results.map(x=>`<div class="matrix-row"><span>${x.Scanner}</span><span class="${x.Result?'yes':'no'}">${x.Result?'🟢 YES':'🔴 NO'}</span></div>`).join('')}catch(e){$('matrix').textContent='Error: '+e.message}}
$('timeframe').onchange=async()=>{await loadSymbols();await loadCandles()};$('scanner').onchange=renderTiles;$('runBtn').onclick=run;$('matrixBtn').onclick=matrix;$('refreshBtn').onclick=async()=>{await loadCandles();$('status').textContent='🟢 Latest timestamps refreshed'};$('search').oninput=e=>{const q=e.target.value.toUpperCase();renderTable(lastResults.filter(r=>String(r.Symbol||'').toUpperCase().includes(q)))};$('downloadBtn').onclick=()=>{if(!lastResults.length)return;const cols=Object.keys(lastResults[0]);const csv=[cols.join(','),...lastResults.map(r=>cols.map(c=>JSON.stringify(r[c]??'')).join(','))].join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));a.download='scanner_results.csv';a.click()};init();